---
title: "Julia's code for later usage?"
author: "Emily Morris"
date: "March 20, 2018"
output: html_document
---



```{r,message=FALSE, warning=FALSE}
#grouping by district and states
state_district<-house_elections %>%
  group_by(state,district)%>%
  summarise(gen_total=sum(general_votes),
            runoff_total=sum(runoff_votes), 
            primary_total = sum(primary_votes))
head(state_district, n=10)

#merge(joining state_district and house elections by both state and district)
vote_percent<-house_elections %>%
 merge(state_district, by = c("state","district")) %>%
  group_by(fec_id,ge_winner)%>%
  summarise(ratio=(general_votes/gen_total), 
            percent = (general_votes/gen_total)*100) #vote percentage got in general election for each candidate



```

```{r,message=FALSE, warning=FALSE}
 #filtering candidates to only be house and running in 2012
H_candidates_2012 <- candidates %>%
  filter(cand_office == "H",cand_election_yr==2012) %>%
  rename("candidate_name" = "cand_name") %>% 
  rename("fec_id" = "cand_id") #renaming cand_id to be fec_id so we can join 

 #summarise house candidates (total primary, total general votes, overall total votes)
percent_votes<-H_candidates_2012 %>%
 left_join(house_elections, by = "fec_id")%>%
   group_by(fec_id) %>%
summarize(Total_primary = sum(primary_votes), Total_general = sum(general_votes), total= Total_primary + Total_general)

candidates_2012 <- candidates %>%
  filter(cand_office == "H",cand_election_yr==2012) %>%
  rename("candidate_name" = "cand_name") %>% #renaming 
  rename("fec_id" = "cand_id") %>%
 full_join(percent_votes, by = "fec_id") 

candidates_2012_house<-candidates_2012%>%
  full_join(vote_percent, by = "fec_id")

#joining committees and contrabutions 
committees_contributions <- committees %>%
 full_join(contributions, by = "cmte_id")%>%
rename( "fec_id" ="cand_id.y")

#joining contrabutions and  2012 house candidates
contrabutions_candidates<-candidates_2012_house %>%
  left_join(committees_contributions, by = "fec_id")%>%
  group_by(candidate_name,cand_party_affiliation,cand_city,cand_office_district, fec_id, cand_office_state, Total_primary, Total_general,percent, total)%>%
  filter(cand_party_affiliation == "DEM"|cand_party_affiliation == "REP") %>% 
  mutate(transaction=sum(transaction_amt)) %>%
  filter(percent > 1 )

```


```{r,message=FALSE, warning=FALSE}
#grouping by state and district 
Data1<-contrabutions_candidates%>%
  group_by(cand_office_district, cand_office_state, transaction)%>%
  summarize(Total = sum(Total_general), 
            D = sum(ifelse(cand_party_affiliation == "DEM", Total_general, 0)), 
            R = sum(ifelse(cand_party_affiliation == "REP", Total_general , 0)), 
            Prop_dem = ((100*D)/Total), 
            Prop_R = ((100*R)/Total), 
            margin = abs(Prop_dem - Prop_R/Total))%>%
  mutate(winning_party = ifelse((Prop_dem > 50), "D", "R"))



# this function filters for state 
state_filter <-function(state_arg){Data1 %>%
    filter(cand_office_state == state_arg)}

# this function creates a ggplot where each dot is a district and the color is the party that won the district  and the size is the victory of margin and the x-axis = number of total ballots cast in each district and the y-axis = total amount of money spent in each district. 
plot_filter<-function(data_a){print(ggplot(data=data_a, aes(x=transaction, y =Total )) + 
  geom_point(aes(fill = winning_party, size = margin ), alpha=0.45, shape = 21, color="black", stroke = 1.29, position=position_dodge(width=0.7)) +
  scale_fill_manual(values = c("D" = "darkblue", "R" = "red"),"Party that won the district") +
    ggtitle(data_a$cand_office_state)+
    scale_y_continuous("Amount of Money Spent")+
  scale_x_continuous("Total ballots cast") +
    scale_size_continuous(range = c(1.725, 4.75),"Margin of Victoy(%)")+
    theme(axis.ticks.length = unit(4, "mm"), axis.ticks.y = element_blank()))}
     

#example:
plot_filter(state_filter("NJ"))
```
This graph shows the interaction between money spent, total ballots cast, and margin of victory, shown by district as well as party. The take home message of this particular graph is that in New Jersey, there was no true relationship between any of the variables, other than the fact that in this state, democrats were generally winning by greater margins. 
```{r, message=FALSE, warning=FALSE}
#plotting all states: 
lapply(lapply(Data1$cand_office_state,state_filter), plot_filter)
  
```
