---
title: "Mini-Project 2"
author: "Sylvie, Julia and Emily"
date: "March 7, 2018"
output: 
  html_document:
    code_folding: hide
---
```{r setup, include=FALSE, message=FALSE}
library(tidyverse)
library(ggplot2)
library(ggthemes)
library(RColorBrewer)
library(extrafont)
#install.packages("gridExtra")
library("gridExtra")
#install.packages("ggpubr")
library(ggpubr)
library(dplyr)
```

```{r, include=FALSE,message=FALSE}
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
#load("individuals.rda")
```



```{r,message=FALSE, warning=FALSE}
#grouping by district and states
state_district<-house_elections %>%
  group_by(state,district)%>%
  summarise(gen_total=sum(general_votes),
            runoff_total=sum(runoff_votes), 
            primary_total = sum(primary_votes))
head(state_district, n=10)

#merge(joining state_district and house elections by both state and district)
vote_percent<-house_elections %>%
 merge(state_district, by = c("state","district")) %>%
  group_by(fec_id,ge_winner)%>%
  summarise(ratio=(general_votes/gen_total), 
            percent = (general_votes/gen_total)*100) #vote percentage got in general election for each candidate



```

```{r,message=FALSE, warning=FALSE}
 #filtering candidates to only be house and running in 2012
H_candidates_2012 <- candidates %>%
  filter(cand_office == "H",cand_election_yr==2012) %>%
  rename("candidate_name" = "cand_name") %>% 
  rename("fec_id" = "cand_id") #renaming cand_id to be fec_id so we can join 

 #summarise house candidates (total primary, total general votes, overall total votes)
percent_votes<-H_candidates_2012 %>%
 left_join(house_elections, by = "fec_id")%>%
   group_by(fec_id) %>%
summarize(Total_primary = sum(primary_votes), Total_general = sum(general_votes), total= Total_primary + Total_general)

candidates_2012 <- candidates %>%
  filter(cand_office == "H",cand_election_yr==2012) %>%
  rename("candidate_name" = "cand_name") %>% #renaming 
  rename("fec_id" = "cand_id") %>%
 full_join(percent_votes, by = "fec_id") 

candidates_2012_house<-candidates_2012%>%
  full_join(vote_percent, by = "fec_id")

#joining committees and contrabutions 
committees_contributions <- committees %>%
 full_join(contributions, by = "cmte_id")%>%
rename( "fec_id" ="cand_id.y")

#joining contrabutions and  2012 house candidates
contrabutions_candidates<-candidates_2012_house %>%
  left_join(committees_contributions, by = "fec_id")%>%
  group_by(candidate_name,cand_party_affiliation,cand_city,cand_office_district, fec_id, cand_office_state, Total_primary, Total_general,percent, total)%>%
  filter(cand_party_affiliation == "DEM"|cand_party_affiliation == "REP") %>% 
  mutate(transaction=sum(transaction_amt)) %>%
  filter(percent > 1 )

```


```{r,message=FALSE, warning=FALSE}
#grouping by state and district 
Data1<-contrabutions_candidates%>%
  group_by(cand_office_district, cand_office_state, transaction)%>%
  summarize(Total = sum(Total_general), 
            D = sum(ifelse(cand_party_affiliation == "DEM", Total_general, 0)), 
            R = sum(ifelse(cand_party_affiliation == "REP", Total_general , 0)), 
            Prop_dem = ((100*D)/Total), 
            Prop_R = ((100*R)/Total), 
            margin = abs(Prop_dem - Prop_R/Total))%>%
  mutate(winning_party = ifelse((Prop_dem > 50), "D", "R"))



# this function filters for state 
state_filter <-function(state_arg){Data1 %>%
    filter(cand_office_state == state_arg)}

# this function creates a ggplot where each dot is a district and the color is the party that won the district  and the size is the victory of margin and the x-axis = number of total ballots cast in each district and the y-axis = total amount of money spent in each district. 
plot_filter<-function(data_a){print(ggplot(data=data_a, aes(x=transaction, y =Total )) + 
  geom_point(aes(fill = winning_party, size = margin ), alpha=0.45, shape = 21, color="black", stroke = 1.29, position=position_dodge(width=0.7)) +
  scale_fill_manual(values = c("D" = "darkblue", "R" = "red"),"Party that won the district") +
    ggtitle(data_a$cand_office_state)+
    scale_y_continuous("Amount of Money Spent")+
  scale_x_continuous("Total ballots cast") +
    scale_size_continuous(range = c(1.725, 4.75),"Margin of Victoy(%)")+
    theme(axis.ticks.length = unit(4, "mm"), axis.ticks.y = element_blank()))}
     

#example:
plot_filter(state_filter("NJ"))
```

```{r, message=FALSE, warning=FALSE}
#plotting all states: 
lapply(lapply(Data1$cand_office_state,state_filter), plot_filter)
  
```
```{r, message= FALSE, warning= FALSE}
contributions_and_elections <- house_elections %>%
  rename("cand_id"= fec_id)%>%
  full_join(contributions, by= "cand_id")%>%
  select(cand_id:ge_winner, transaction_amt)%>%
  rename("state"=state.x)

house_winners_incumbents_DEMS <- contributions_and_elections %>%
  filter(ge_winner== "W", incumbent== "TRUE", transaction_amt > 0, party== "D")%>%
  group_by(state)%>%
  summarise(total_winnners_per_state= n(),
            avg_contribution=mean(transaction_amt))%>%
  rename("Dem_Incumbent_Winners"= total_winnners_per_state, "Dem_Incumbent_Contribution"= avg_contribution)


house_winners_challengers_DEMS <- contributions_and_elections %>%
  filter(ge_winner == "W", incumbent == "FALSE", transaction_amt > 0, party== "D")%>%
  group_by(state)%>%
  summarise(total_winners_per_state= n(),
            avg_contribution = mean(transaction_amt))%>%
  rename("Dem_Challenger_Winners"= total_winners_per_state, "Dem_Challenger_Contributions"= avg_contribution)

Dem_Winners <- house_winners_incumbents_DEMS %>%
  left_join(house_winners_challengers_DEMS, by="state")

house_winners_incumbents_REPS <- contributions_and_elections %>%
  filter(ge_winner== "W", incumbent== "TRUE", transaction_amt > 0, party== "R")%>%
  group_by(state)%>%
  summarise(total_winnners_per_state= n(),
            avg_contribution=mean(transaction_amt))%>%
  rename("REP_Incumbent_Winners"= total_winnners_per_state, "REP_Incumbent_Contribution"= avg_contribution)

house_winners_challengers_REPS <- contributions_and_elections %>%
  filter(ge_winner == "W", incumbent == "FALSE", transaction_amt > 0, party== "R")%>%
  group_by(state)%>%
  summarise(total_winners_per_state= n(),
            avg_contribution = mean(transaction_amt))%>%
  rename("REP_Challenger_Winners"= total_winners_per_state, "REP_Challenger_Contributions"= avg_contribution)

REP_Winners <- house_winners_incumbents_REPS %>%
  left_join(house_winners_challengers_REPS, by="state")

house_winners_all <- REP_Winners %>%
  full_join(Dem_Winners, by= "state")
```

```{r}
number_of_winners <- house_winners_all %>%
  select(state:REP_Incumbent_Winners, REP_Challenger_Winners, Dem_Incumbent_Winners, Dem_Challenger_Winners)%>%
  rename("REP_Challengers"= REP_Challenger_Winners, "REP_Incumbents"= REP_Incumbent_Winners,"DEM_Challengers"= Dem_Challenger_Winners, "DEM_Incumbents"= Dem_Incumbent_Winners)%>%
  gather(Winner_Type, Number_of_winners, -state)
```

```{r}
average_contributions <- house_winners_all %>%
  select(state:REP_Incumbent_Contribution, REP_Challenger_Contributions, Dem_Incumbent_Contribution, Dem_Challenger_Contributions)%>%
  rename("REP_Challengers"= REP_Challenger_Contributions, "REP_Incumbents"= REP_Incumbent_Contribution,"DEM_Challengers"= Dem_Challenger_Contributions, "DEM_Incumbents"= Dem_Incumbent_Contribution)%>%
  gather(Winner_Type, avg_contributions, -state)
```

```{r}
winners <- number_of_winners%>%
  merge(average_contributions, by=c("state","Winner_Type"))%>%
  na.omit()
```


```{r, message=FALSE, warning= FALSE}

winners_plot_by_state <- function(name_arg) {
  winners%>%
    filter(state==name_arg)}
```

```{r, message= FALSE, warning= FALSE}

ggplot(winners, aes(x= avg_contributions, y= Number_of_winners))+
  geom_point(aes(shape= Winner_Type, fill= Winner_Type), alpha= 0.45, size= 3)+
   scale_fill_manual(values = c("REP_Incumbents" = "red", "REP_Challengers" = "red", "DEM_Incumbents"="darkblue", "DEM_Challengers"= "darkblue"))+
  scale_shape_manual(values= c("REP_Incumbents"= 24, "DEM_Incumbents"=24, "REP_Challengers"= 21, "DEM_Challengers"=21))+
  scale_x_log10()+
  scale_y_log10()+
  xlab("Total Winners")+
  ylab("Average Contributions")

```

